import type { Practice4Question } from "./practice4.types";

export const practice4Questions: Practice4Question[] = [
  {
    id: 1,
    category: "Identificación de metadatos",
    kind: "selectJustify",
    scenario:
      "TÍTULO: Informe técnico sobre gestión documental\nCÓDIGO: IT-2026-015\nFECHA: 15/08/2026\nUNIDAD: Gestión Documental\nASUNTO: Evaluación de documentos electrónicos\nRESPONSABLE: Especialista de la unidad",
    prompt: "Identifica cuáles de los siguientes datos funcionan como metadatos y explica brevemente por qué.",
    points: 1,
    options: [
      { id: "titulo", label: "Título" },
      { id: "codigo", label: "Código" },
      { id: "fecha", label: "Fecha" },
      { id: "unidad", label: "Unidad" },
      { id: "asunto", label: "Asunto" },
      { id: "responsable", label: "Responsable" },
      { id: "contenido", label: "El contenido narrativo del informe" },
      { id: "pagina", label: "El número de página" },
    ],
    correctIds: ["titulo", "codigo", "fecha", "unidad", "asunto", "responsable"],
    minSelected: 5,
    justifyPrompts: ["Explica brevemente por qué los elementos que elegiste funcionan como metadatos."],
    justifyMinWords: 6,
    expectedSummary: "Título, código, fecha, unidad, asunto y responsable — datos que identifican, describen, contextualizan o gestionan el documento (no el contenido narrativo ni la paginación).",
    feedbackByVerdict: {
      correct:
        "Correcto: reconoces que un metadato no es el contenido del documento, sino la información que permite identificarlo, describirlo, gestionarlo o contextualizarlo — por eso el título, código, fecha, unidad, asunto y responsable cuentan, pero el texto narrativo o la paginación no.",
      partial:
        "Vas en la dirección correcta, pero revisa tu selección: algunos de los datos elegidos no cumplen función de metadato (como el contenido narrativo), o dejaste fuera alguno de los que sí la cumplen. Refuerza también tu justificación.",
      review:
        "Un metadato es un dato que identifica, describe, gestiona o contextualiza el documento — no el contenido mismo. Revisa la ficha: título, código, fecha, unidad, asunto y responsable son metadatos; el texto narrativo del informe no lo es.",
    },
  },
  {
    id: 2,
    category: "Metadatos faltantes",
    kind: "openText",
    scenario: "TÍTULO: Informe técnico\nFECHA: 15/08/2026\nTIPO DOCUMENTAL: Informe técnico\nASUNTO: Gestión documental",
    prompt: "¿Qué información sería necesario agregar para mejorar la identificación y gestión del documento? Propón al menos 3 metadatos.",
    points: 1,
    fieldLabel: "Metadatos que agregarías",
    candidates: [
      { id: "autor", label: "Autor / productor", keywords: ["autor", "productor", "responsable", "unidad"] },
      { id: "codigo", label: "Código / identificador", keywords: ["codigo", "identificador", "numero"] },
      { id: "expediente", label: "Relación con expediente", keywords: ["expediente"] },
      { id: "destinatario", label: "Destinatario", keywords: ["destinatario", "dirigido"] },
      { id: "acceso", label: "Nivel de acceso", keywords: ["acceso", "confidencial", "publico", "reservado"] },
      { id: "estado", label: "Estado del documento", keywords: ["estado", "tramite"] },
    ],
    requiredCount: 3,
    minWords: 8,
    expectedSummary: "Autor/productor, código/identificador, relación con expediente, destinatario, nivel de acceso o estado del documento.",
    feedbackByVerdict: {
      correct:
        "Correcto: identificas que sin autor, código o relación con expediente el documento queda pobremente identificado y difícil de ubicar dentro del sistema de gestión documental.",
      partial:
        "Propones metadatos razonables, pero podrías ampliar la lista o explicar mejor por qué mejoran la identificación y gestión del documento.",
      review:
        "Piensa qué necesitas saber para encontrar y gestionar este documento en el futuro: ¿quién lo produjo?, ¿con qué código se identifica?, ¿a qué expediente pertenece?, ¿quién puede acceder a él?",
    },
  },
  {
    id: 3,
    category: "Clasificación de metadatos",
    kind: "dragClassify",
    prompt: "Clasifica cada metadato según la función que cumple.",
    points: 1,
    items: [
      { id: "identificador", label: "Identificador", icon: "FileSignature", category: "identificacion" },
      { id: "titulo", label: "Título", icon: "FileText", category: "descripcion" },
      { id: "fecha-creacion", label: "Fecha de creación", icon: "FileSearch", category: "descripcion" },
      { id: "autor", label: "Autor", icon: "KeyRound", category: "contexto" },
      { id: "unidad", label: "Unidad responsable", icon: "Database", category: "contexto" },
      { id: "expediente", label: "Relación con expediente", icon: "FolderOpen", category: "contexto" },
      { id: "acceso", label: "Nivel de acceso", icon: "KeyRound", category: "gestion" },
      { id: "historial", label: "Historial de modificaciones", icon: "ShieldCheck", category: "preservacion" },
    ],
    categories: [
      { id: "identificacion", label: "Identificación", icon: "FileSignature" },
      { id: "descripcion", label: "Descripción", icon: "FileSearch" },
      { id: "gestion", label: "Gestión", icon: "ClipboardList" },
      { id: "contexto", label: "Contexto", icon: "Link2" },
      { id: "preservacion", label: "Preservación", icon: "ShieldCheck" },
    ],
    expectedSummary: "Identificador→Identificación; Título/Fecha de creación→Descripción; Autor/Unidad/Expediente→Contexto; Nivel de acceso→Gestión; Historial de modificaciones→Preservación.",
    feedbackByVerdict: {
      correct: "Correcto: distingues con claridad las cinco funciones de los metadatos según ISO 23081-1 — identificar, describir, gestionar, contextualizar y preservar.",
      partial: "Clasificaste correctamente varios elementos, pero conviene repasar la diferencia entre metadatos de contexto (quién y dónde se produjo) y de gestión (cómo se administra en su ciclo de trámite).",
      review: "Repasa las cinco categorías: identificación (qué lo distingue), descripción (de qué trata), gestión (cómo se administra), contexto (quién y en qué circunstancia lo produjo) y preservación (cómo se conserva en el tiempo).",
    },
  },
  {
    id: 4,
    category: "Calidad de los metadatos",
    kind: "openText",
    scenario: "TÍTULO: Documento\nAUTOR: Juan\nFECHA: 2026\nCÓDIGO: 123\nTIPO: Archivo",
    prompt: "Identifica al menos 3 problemas de esta ficha y propón cómo corregirlos.",
    points: 1,
    fieldLabel: "Problemas detectados y propuesta de corrección",
    candidates: [
      { id: "titulo-generico", label: "Título demasiado genérico", keywords: ["titulo", "generico", "vago", "impreciso"] },
      { id: "autor-incompleto", label: "Autor incompleto (falta apellido/unidad)", keywords: ["autor", "apellido", "incompleto", "nombre"] },
      { id: "fecha-incompleta", label: "Fecha incompleta (solo el año)", keywords: ["fecha", "incompleta", "dia", "mes", "año"] },
      { id: "codigo-insuficiente", label: "Código insuficiente / no estructurado", keywords: ["codigo", "estructurado", "insuficiente", "corto"] },
      { id: "tipo-impreciso", label: "Tipo documental impreciso ('Archivo' no es un tipo documental)", keywords: ["tipo", "impreciso", "archivo"] },
      { id: "falta-asunto", label: "Falta el asunto", keywords: ["asunto", "falta"] },
    ],
    requiredCount: 3,
    minWords: 10,
    expectedSummary: "Título genérico, autor sin apellido/unidad, fecha incompleta, código sin estructura reconocible y 'Archivo' como tipo documental impreciso.",
    feedbackByVerdict: {
      correct: "Correcto: detectas que la vaguedad de estos datos (título, autor, fecha, código y tipo) compromete la identificación y recuperación futura del documento, y propones valores más específicos.",
      partial: "Identificas parte del problema, pero puedes precisar más tus propuestas de corrección o detectar algún problema adicional en la ficha.",
      review: "Observa cada campo por separado: ¿el título dice algo específico?, ¿el autor tiene nombre y apellido?, ¿la fecha tiene día y mes?, ¿el código distingue a este documento de otros?, ¿'Archivo' es realmente un tipo documental?",
    },
  },
  {
    id: 5,
    category: "Selección de metadatos indispensables",
    kind: "selectJustify",
    scenario: "Un documento electrónico va a incorporarse a un sistema de gestión documental.",
    prompt: "De la siguiente lista de posibles metadatos, elige los que consideras indispensables para este documento.",
    points: 1,
    options: [
      { id: "titulo", label: "Título" },
      { id: "fecha", label: "Fecha" },
      { id: "autor", label: "Autor" },
      { id: "codigo", label: "Código" },
      { id: "asunto", label: "Asunto" },
      { id: "unidad", label: "Unidad responsable" },
      { id: "acceso", label: "Nivel de acceso" },
      { id: "color", label: "Color de fondo del documento" },
      { id: "palabras", label: "Cantidad de palabras del documento" },
    ],
    correctIds: ["titulo", "fecha", "autor", "codigo", "asunto", "unidad", "acceso"],
    minSelected: 5,
    justifyPrompts: ["Justifica tu primera elección.", "Justifica tu segunda elección."],
    justifyMinWords: 6,
    expectedSummary: "Título, fecha, autor, código, asunto, unidad responsable y nivel de acceso — no el color de fondo ni el conteo de palabras, que no cumplen función de gestión documental.",
    feedbackByVerdict: {
      correct: "Correcto: reconoces qué metadatos son funcionalmente indispensables para gestionar el documento y descartas atributos superficiales que no aportan a su identificación, descripción o gestión.",
      partial: "Tu selección es en parte acertada; revisa si incluiste algún dato sin función documental o si te faltó alguno de los indispensables.",
      review: "Pregúntate: ¿este dato ayuda a identificar, describir, gestionar o dar contexto al documento? El color de fondo o el conteo de palabras no cumplen ninguna de esas funciones.",
    },
  },
  {
    id: 6,
    category: "Construcción de una ficha",
    kind: "reorder",
    prompt: "Ordena la siguiente información para construir una ficha de metadatos coherente, de lo más identificador a lo más descriptivo del contexto.",
    points: 1,
    items: [
      { id: "asunto", label: "Asunto" },
      { id: "autor", label: "Autor" },
      { id: "unidad", label: "Unidad responsable" },
      { id: "titulo", label: "Título" },
      { id: "fecha", label: "Fecha" },
      { id: "codigo", label: "Código" },
    ],
    correctOrder: ["titulo", "codigo", "fecha", "autor", "unidad", "asunto"],
    expectedSummary: "Título → Código → Fecha → Autor → Unidad responsable → Asunto.",
    feedbackByVerdict: {
      correct: "Correcto: organizas la ficha comenzando por lo que identifica al documento (título, código), siguiendo por su ubicación temporal y de responsabilidad (fecha, autor, unidad) y cerrando con el contenido (asunto).",
      partial: "Tu orden se acerca a una secuencia razonable, pero algunos elementos podrían ubicarse mejor según su función: primero lo que identifica, luego lo que sitúa en el tiempo y la responsabilidad, y al final el contenido.",
      review: "No existe un único orden válido en la práctica, pero para construir una ficha de forma coherente conviene ir de lo más identificador (título, código) a lo más contextual (autor, unidad, asunto).",
    },
  },
  {
    id: 7,
    category: "Documento vs. expediente",
    kind: "dragClassify",
    prompt: "Decide si cada metadato corresponde al expediente o al documento individual.",
    points: 1,
    items: [
      { id: "num-expediente", label: "Número de expediente", icon: "FolderOpen", category: "expediente" },
      { id: "estado-expediente", label: "Estado del expediente", icon: "Activity", category: "expediente" },
      { id: "unidad-responsable", label: "Unidad responsable del trámite", icon: "Database", category: "expediente" },
      { id: "titulo-doc", label: "Título del documento", icon: "FileText", category: "documento" },
      { id: "fecha-doc", label: "Fecha del documento", icon: "FileSearch", category: "documento" },
      { id: "tipo-doc", label: "Tipo documental", icon: "FileType", category: "documento" },
    ],
    categories: [
      { id: "expediente", label: "Al expediente", icon: "FolderOpen" },
      { id: "documento", label: "Al documento", icon: "FileText" },
    ],
    justifyPrompt: "Justifica una de tus decisiones.",
    expectedSummary: "Número de expediente, estado del expediente y unidad responsable del trámite → al expediente. Título, fecha y tipo documental → al documento individual.",
    feedbackByVerdict: {
      correct: "Correcto: distingues los metadatos que describen el conjunto del trámite (el expediente) de los que describen cada pieza documental individual — clave para entender la relación documento-expediente.",
      partial: "Clasificaste bien parte de los elementos; recuerda que el expediente agrupa el trámite en su conjunto, mientras que cada documento conserva sus propios datos de identificación.",
      review: "El expediente es el conjunto que agrupa el trámite (número, estado, unidad responsable del trámite); el documento individual conserva sus propios datos (título, fecha, tipo documental).",
    },
  },
  {
    id: 8,
    category: "Caso profesional",
    kind: "openText",
    scenario: "Una institución tiene miles de documentos electrónicos. Muchos tienen títulos genéricos como 'Informe', 'Oficio' o 'Documento final'. Los usuarios tienen dificultades para encontrar información.",
    prompt: "¿Qué problema relacionado con los metadatos observas? Identifica el problema y propón al menos dos medidas.",
    points: 1,
    fieldLabel: "Problema y medidas propuestas",
    candidates: [
      { id: "descripcion-pobre", label: "Metadatos descriptivos insuficientes o poco específicos", keywords: ["descriptivo", "generico", "especifico", "titulo"] },
      { id: "recuperacion", label: "Dificultad de recuperación / búsqueda", keywords: ["recuperacion", "busqueda", "encontrar", "localizar"] },
      { id: "politica-titulado", label: "Definir una política o convención de titulado", keywords: ["politica", "convencion", "norma", "estandar"] },
      { id: "palabras-clave", label: "Incorporar metadatos de asunto o palabras clave", keywords: ["asunto", "palabra clave", "descriptor"] },
      { id: "capacitacion", label: "Capacitar al personal que registra los documentos", keywords: ["capacitacion", "capacitar", "formacion"] },
    ],
    requiredCount: 3,
    minWords: 15,
    expectedSummary: "El problema es la pobreza de los metadatos descriptivos (títulos genéricos), que dificulta la recuperación; medidas: política de titulado, metadatos de asunto/palabras clave, capacitación del personal.",
    feedbackByVerdict: {
      correct: "Correcto: identificas que los títulos genéricos son un problema de calidad de los metadatos descriptivos que afecta directamente la recuperación de información, y propones medidas concretas y razonables.",
      partial: "Identificas parte del problema; profundiza en el vínculo entre metadatos descriptivos pobres y dificultad de recuperación, y propone medidas más concretas.",
      review: "El problema central es de calidad de los metadatos descriptivos: títulos genéricos no permiten diferenciar documentos ni recuperarlos. Piensa en medidas como una política de titulado o el uso de palabras clave.",
    },
  },
  {
    id: 9,
    category: "Comparación de documentos",
    kind: "compareChoice",
    prompt: "¿Cuál de los dos documentos presenta mejores condiciones para su identificación y recuperación? Justifica tu respuesta.",
    points: 1,
    labelA: "Documento A",
    labelB: "Documento B",
    rowsA: [
      { field: "Título", value: "Informe" },
      { field: "Fecha", value: "2026" },
      { field: "Autor", value: "Carlos" },
      { field: "Código", value: "15" },
    ],
    rowsB: [
      { field: "Título", value: "Informe técnico de evaluación documental" },
      { field: "Fecha", value: "15/08/2026" },
      { field: "Autor", value: "Carlos Injante Pérez" },
      { field: "Código", value: "IT-2026-015" },
      { field: "Unidad", value: "Gestión Documental" },
    ],
    expected: "b",
    justifyMinWords: 8,
    expectedSummary: "Documento B, con una justificación que explique cómo la especificidad de sus metadatos facilita identificarlo y recuperarlo.",
    feedbackByVerdict: {
      correct: "Correcto: el Documento B tiene una fecha completa, un autor identificable, un código estructurado y unidad productora — condiciones que facilitan su identificación y recuperación, y tu justificación lo sustenta con criterio.",
      partial: "Tu justificación muestra razonamiento, aunque conviene reforzar cómo la especificidad de los metadatos del Documento B mejora su identificación y recuperación frente al Documento A.",
      review: "No basta con marcar A o B: explica tu decisión. Compara la especificidad de cada metadato (fecha completa vs. solo año, autor identificable vs. solo un nombre, código estructurado vs. un número aislado).",
    },
  },
  {
    id: 10,
    category: "Trazabilidad",
    kind: "selectJustify",
    scenario: "Secuencia del documento: Creación → Registro → Tramitación → Modificación → Firma → Derivación → Archivo.",
    prompt: "¿Qué metadatos permitirían reconstruir las acciones realizadas sobre el documento? Selecciona al menos 4.",
    points: 1,
    options: [
      { id: "fecha-accion", label: "Fecha de cada acción" },
      { id: "usuario", label: "Usuario o responsable de la acción" },
      { id: "tipo-accion", label: "Tipo de acción realizada" },
      { id: "estado-resultante", label: "Estado resultante" },
      { id: "unidad-interviniente", label: "Unidad interviniente" },
      { id: "identificador", label: "Identificador del documento" },
      { id: "color-icono", label: "Color del ícono en el sistema" },
      { id: "tamano-archivo", label: "Tamaño del archivo" },
    ],
    correctIds: ["fecha-accion", "usuario", "tipo-accion", "estado-resultante", "unidad-interviniente", "identificador"],
    minSelected: 4,
    justifyPrompts: ["Justifica uno de los metadatos que seleccionaste, explicando cómo ayuda a reconstruir la trazabilidad."],
    justifyMinWords: 6,
    expectedSummary: "Fecha de cada acción, usuario responsable, tipo de acción, estado resultante, unidad interviniente e identificador del documento.",
    feedbackByVerdict: {
      correct: "Correcto: identificas que reconstruir la trazabilidad requiere saber cuándo, quién, qué acción y con qué resultado — el color del ícono o el tamaño del archivo no aportan a esa reconstrucción.",
      partial: "Tu selección incluye elementos relevantes, pero revisa si te faltó alguno clave (fecha, usuario, tipo de acción, estado) o si incluiste un dato sin relación con la trazabilidad.",
      review: "Para reconstruir qué pasó con un documento necesitas saber cuándo ocurrió cada acción, quién la realizó, qué tipo de acción fue y qué estado resultó — no atributos visuales o de tamaño del archivo.",
    },
  },
  {
    id: 11,
    category: "Metadato y finalidad",
    kind: "matchPairs",
    prompt: "Relaciona cada metadato con la finalidad que cumple.",
    points: 1,
    concepts: [
      { id: "identificador", label: "Identificador" },
      { id: "fecha", label: "Fecha" },
      { id: "autor", label: "Autor" },
      { id: "acceso", label: "Nivel de acceso" },
      { id: "unidad", label: "Unidad" },
    ],
    definitions: [
      { id: "d1", label: "Distinguir el documento de forma única" },
      { id: "d2", label: "Ubicarlo temporalmente" },
      { id: "d3", label: "Conocer su procedencia y responsabilidad" },
      { id: "d4", label: "Controlar su disponibilidad" },
      { id: "d5", label: "Conocer el contexto institucional de producción" },
    ],
    correctPairs: { identificador: "d1", fecha: "d2", autor: "d3", acceso: "d4", unidad: "d5" },
    expectedSummary: "Identificador→distinguir; Fecha→ubicar en el tiempo; Autor→procedencia; Nivel de acceso→disponibilidad; Unidad→contexto institucional.",
    feedbackByVerdict: {
      correct: "Correcto: relacionas con precisión cada metadato con la finalidad que cumple dentro de la gestión documental.",
      partial: "Relacionaste correctamente varios pares; revisa la diferencia entre 'procedencia' (autor) y 'contexto institucional' (unidad), que suelen confundirse.",
      review: "Piensa en la función específica de cada metadato: identificar de forma única, ubicar en el tiempo, indicar procedencia, controlar acceso o dar contexto institucional.",
    },
  },
  {
    id: 12,
    category: "Análisis de una ficha",
    kind: "selectJustify",
    scenario: "TÍTULO: Informe de seguimiento presupuestal\nCÓDIGO: INF-2026-102\nFECHA: 20/07/2026\nAUTOR: Rosa Ibáñez\nUNIDAD: Planeamiento\nASUNTO: Seguimiento del gasto del segundo trimestre\nESTADO: En trámite\nNIVEL DE ACCESO: Uso interno",
    prompt: "¿Qué metadatos de esta ficha ayudan principalmente a identificar el documento?",
    points: 1,
    options: [
      { id: "titulo", label: "Título" },
      { id: "codigo", label: "Código" },
      { id: "fecha", label: "Fecha" },
      { id: "autor", label: "Autor" },
      { id: "unidad", label: "Unidad" },
      { id: "asunto", label: "Asunto" },
      { id: "estado", label: "Estado" },
      { id: "acceso", label: "Nivel de acceso" },
    ],
    correctIds: ["titulo", "codigo", "fecha"],
    minSelected: 2,
    justifyPrompts: ["Explica por qué esos metadatos son los que más contribuyen a identificar este documento."],
    justifyMinWords: 6,
    expectedSummary: "Título, código y fecha — la combinación que distingue a este documento de otros similares (el resto describe, gestiona o contextualiza, pero no identifica en sentido estricto).",
    feedbackByVerdict: {
      correct: "Correcto: el código es el identificador más fuerte, y el título junto con la fecha completan la identificación al distinguir el documento de otros similares producidos por la misma unidad.",
      partial: "Tu selección incluye elementos válidos, pero conviene distinguir mejor entre metadatos que identifican (título, código, fecha) y los que cumplen otras funciones (autor y unidad dan contexto; estado y acceso son de gestión).",
      review: "La identificación estricta responde a '¿qué documento es exactamente y cómo lo distingo de otro parecido?' — eso lo resuelven principalmente el código, el título y la fecha.",
    },
  },
  {
    id: 13,
    category: "Recuperación de información",
    kind: "openText",
    scenario: "Un usuario busca un informe emitido por una determinada unidad durante agosto de 2026, pero el sistema solo registra como título 'Informe'.",
    prompt: "¿Qué metadatos adicionales facilitarían la recuperación de este documento?",
    points: 1,
    fieldLabel: "Metadatos que facilitarían la recuperación",
    candidates: [
      { id: "unidad", label: "Unidad productora / emisora", keywords: ["unidad", "productora", "emisora"] },
      { id: "fecha-completa", label: "Fecha completa", keywords: ["fecha", "completa", "dia", "mes"] },
      { id: "asunto", label: "Asunto específico", keywords: ["asunto", "especifico", "tema"] },
      { id: "tipo", label: "Tipo documental", keywords: ["tipo documental", "tipo"] },
      { id: "codigo", label: "Código / identificador", keywords: ["codigo", "identificador"] },
      { id: "palabras-clave", label: "Palabras clave / descriptores", keywords: ["palabra clave", "descriptor", "etiqueta"] },
    ],
    requiredCount: 3,
    minWords: 12,
    expectedSummary: "Unidad productora, fecha completa, asunto específico, tipo documental, código o palabras clave.",
    feedbackByVerdict: {
      correct: "Correcto: reconoces que la unidad productora, la fecha completa y un asunto específico son justamente los filtros que el usuario necesitaba y que el sistema no tenía registrados.",
      partial: "Propones metadatos razonables; profundiza en cómo cada uno resolvería específicamente la búsqueda descrita en el caso.",
      review: "Relee el caso: el usuario busca por unidad y por fecha (agosto de 2026), pero el título 'Informe' no distingue nada. ¿Qué metadatos permitirían filtrar por esos criterios?",
    },
  },
  {
    id: 14,
    category: "Ambigüedad en los metadatos",
    kind: "editFields",
    scenario: "TÍTULO: Informe final\nAUTOR: María\nFECHA: 2026\nCÓDIGO: INF-01",
    prompt: "Esta ficha contiene información demasiado genérica o ambigua. Propón valores más precisos para cada campo.",
    points: 1,
    fields: [
      { id: "titulo", label: "Título", initialValue: "Informe final" },
      { id: "autor", label: "Autor", initialValue: "María" },
      { id: "fecha", label: "Fecha", initialValue: "2026" },
      { id: "codigo", label: "Código", initialValue: "INF-01" },
    ],
    explanationPrompt: "Explica por qué esta información resultaba demasiado genérica o ambigua.",
    explanationMinWords: 10,
    expectedSummary: "Valores más específicos: título que indique el asunto real, autor con nombre y apellido (o unidad), fecha completa (día/mes/año) y un código con estructura reconocible.",
    feedbackByVerdict: {
      correct: "Correcto: reemplazas cada valor genérico por uno más específico y explicas por qué la ambigüedad original dificultaba identificar el documento.",
      partial: "Mejoraste algunos campos, pero otros conservan un nivel de generalidad similar al original. Sé más específico en cada valor propuesto.",
      review: "Cada valor original es demasiado genérico: 'Informe final' no dice de qué trata, 'María' no identifica a una persona sin apellido, '2026' no ubica el documento en el tiempo, y 'INF-01' no lo distingue de otros. Propón valores concretos.",
    },
  },
  {
    id: 15,
    category: "Decisión profesional",
    kind: "compareChoice",
    prompt: "¿Cuál estrategia permitiría una gestión documental más completa? Selecciona y justifica.",
    points: 1,
    labelA: "Estrategia A",
    labelB: "Estrategia B",
    rowsA: [{ field: "Alcance", value: "Registrar únicamente título y fecha" }],
    rowsB: [{ field: "Alcance", value: "Registrar identificación, descripción, gestión, contexto y preservación según el propósito del documento" }],
    expected: "b",
    justifyMinWords: 8,
    expectedSummary: "Estrategia B, justificando que una gestión documental completa requiere metadatos de las distintas funciones (identificación, descripción, gestión, contexto y preservación), no solo título y fecha.",
    feedbackByVerdict: {
      correct: "Correcto: una gestión documental completa requiere metadatos que cubran las distintas funciones — no basta con título y fecha para identificar, recuperar, gestionar y preservar un documento a lo largo del tiempo.",
      partial: "Tu justificación tiene elementos válidos; profundiza en por qué limitar los metadatos a título y fecha resulta insuficiente para una gestión documental completa.",
      review: "Piensa en todo lo que necesitas para gestionar un documento a lo largo de su ciclo de vida: no solo identificarlo (título, fecha), sino también describirlo, gestionarlo, contextualizarlo y preservarlo.",
    },
  },
  {
    id: 16,
    category: "Construcción de una ficha por tipo documental",
    kind: "selectJustify",
    scenario: "Tipo documental: Memorando.",
    prompt: "Selecciona al menos 6 metadatos que consideras necesarios para un memorando.",
    points: 1,
    options: [
      { id: "titulo", label: "Título" },
      { id: "fecha", label: "Fecha" },
      { id: "codigo", label: "Código" },
      { id: "remitente", label: "Autor / remitente" },
      { id: "destinatario", label: "Destinatario" },
      { id: "asunto", label: "Asunto" },
      { id: "unidad", label: "Unidad responsable" },
      { id: "acceso", label: "Nivel de acceso" },
      { id: "estado", label: "Estado del trámite" },
      { id: "referencia", label: "Referencia" },
      { id: "color-papel", label: "Color del papel" },
      { id: "fuente", label: "Tipo de letra utilizado" },
    ],
    correctIds: ["titulo", "fecha", "codigo", "remitente", "destinatario", "asunto", "unidad", "acceso", "estado", "referencia"],
    minSelected: 6,
    justifyPrompts: ["Elige uno de los metadatos que seleccionaste y explica por qué es necesario.", "Elige otro metadato distinto y explica por qué es necesario."],
    justifyMinWords: 6,
    expectedSummary: "Título, fecha, código, remitente, destinatario, asunto, unidad responsable, nivel de acceso, estado del trámite y referencia — no atributos de formato como el color del papel o el tipo de letra.",
    feedbackByVerdict: {
      correct: "Correcto: seleccionas metadatos funcionales para un memorando (identificación, descripción, gestión y contexto) y explicas con criterio por qué son necesarios.",
      partial: "Tu selección es mayormente acertada; revisa si incluiste algún atributo sin función documental o si tus justificaciones podrían ser más específicas.",
      review: "Piensa en lo que necesita un memorando para ser identificado, descrito y gestionado dentro de un SGD — no en atributos de formato como el color del papel o la tipografía.",
    },
  },
  {
    id: 17,
    category: "Metadatos y contexto",
    kind: "openText",
    scenario:
      "Un documento tiene un contenido correcto, pero no registra: unidad responsable, asunto, relación con expediente ni autor.",
    prompt: "¿Por qué estos datos pueden ser importantes aunque no formen parte del contenido principal del documento?",
    points: 1,
    fieldLabel: "Explicación",
    candidates: [
      { id: "contexto-produccion", label: "Dan contexto de producción", keywords: ["contexto", "produccion", "origen"] },
      { id: "trazabilidad", label: "Permiten trazabilidad", keywords: ["trazabilidad", "seguimiento", "historial"] },
      { id: "recuperacion", label: "Facilitan la recuperación futura", keywords: ["recuperacion", "busqueda", "encontrar"] },
      { id: "responsabilidad", label: "Sustentan responsabilidad / autenticidad", keywords: ["responsabilidad", "autenticidad", "atribuir"] },
      { id: "relacion-tramite", label: "Vinculan el documento con el trámite/expediente", keywords: ["tramite", "expediente", "relacion"] },
    ],
    requiredCount: 3,
    minWords: 15,
    expectedSummary: "Estos metadatos, aunque externos al contenido, aportan contexto de producción, trazabilidad, capacidad de recuperación y sustento de responsabilidad/autenticidad, y vinculan el documento con su trámite.",
    feedbackByVerdict: {
      correct: "Correcto: comprendes que un documento no se gestiona solo por su contenido — necesita metadatos externos que den contexto, sustenten su autenticidad y permitan encontrarlo y relacionarlo con su trámite.",
      partial: "Tu explicación identifica parte de la importancia de estos metadatos; profundiza en más de una de sus funciones (contexto, trazabilidad, recuperación, responsabilidad, relación con el expediente).",
      review: "Aunque no estén en el texto, estos datos permiten saber quién lo produjo (responsabilidad), en qué trámite se originó (contexto/expediente) y cómo encontrarlo después (recuperación).",
    },
  },
  {
    id: 18,
    category: "Nombre de archivo vs. metadatos",
    kind: "openText",
    scenario: "Documento A: 'Informe.pdf'\nDocumento B: 'IT-2026-015_Evaluacion_Gestion_Documental.pdf'",
    prompt: "¿Qué ventajas presenta el segundo caso desde el punto de vista de identificación y recuperación? Explica, sin confundir el nombre del archivo con los metadatos del documento.",
    points: 1,
    fieldLabel: "Explicación",
    candidates: [
      { id: "identificacion", label: "Facilita la identificación visual del archivo", keywords: ["identificacion", "identificar", "reconocer"] },
      { id: "recuperacion", label: "Facilita la búsqueda/recuperación", keywords: ["recuperacion", "busqueda", "encontrar"] },
      { id: "evita-confusion", label: "Evita confundirlo con otros documentos similares", keywords: ["confusion", "duplicado", "similar"] },
      { id: "no-reemplaza", label: "El nombre del archivo no reemplaza a los metadatos formales del sistema", keywords: ["no reemplaza", "no es metadato", "metadatos del sistema", "no sustituye"] },
    ],
    requiredCount: 3,
    minWords: 15,
    expectedSummary: "El nombre descriptivo ayuda a identificar y ubicar el archivo a simple vista, pero es una convención práctica, no un metadato formal: los metadatos reales deben registrarse en el sistema de gestión documental.",
    feedbackByVerdict: {
      correct: "Correcto: reconoces la ventaja práctica de un nombre de archivo descriptivo y, a la vez, aclaras que no reemplaza a los metadatos formales registrados en el sistema — una distinción clave que evita confundir convención de nomenclatura con gestión de metadatos.",
      partial: "Identificas la ventaja del nombre descriptivo, pero no explicitas que el nombre del archivo no sustituye a los metadatos formales del sistema — esa distinción es central en esta pregunta.",
      review: "Un nombre de archivo descriptivo ayuda a ubicarlo visualmente, pero ojo: no es lo mismo que un metadato del sistema de gestión documental. Explica ambas ideas: la ventaja práctica y esa distinción.",
    },
  },
  {
    id: 19,
    category: "Análisis y corrección de una ficha",
    kind: "editFields",
    scenario: "TÍTULO: Documento\nAUTOR: Ana\nFECHA: 2026\nCÓDIGO: 1\nASUNTO: Vario",
    prompt: "Esta ficha tiene 5 errores. Corrígelos directamente en los campos y luego explica dos de tus correcciones.",
    points: 1,
    fields: [
      { id: "titulo", label: "Título", initialValue: "Documento" },
      { id: "autor", label: "Autor", initialValue: "Ana" },
      { id: "fecha", label: "Fecha", initialValue: "2026" },
      { id: "codigo", label: "Código", initialValue: "1" },
      { id: "asunto", label: "Asunto", initialValue: "Vario" },
    ],
    explanationPrompt: "Explica dos de las correcciones que realizaste.",
    explanationMinWords: 12,
    expectedSummary: "Un título específico, autor con nombre completo, fecha completa, un código estructurado y un asunto concreto (no 'Vario').",
    feedbackByVerdict: {
      correct: "Correcto: corriges los cinco campos con valores más específicos y explicas con claridad por qué esos cambios mejoran la calidad de la ficha.",
      partial: "Corregiste parte de la ficha; revisa los campos que aún conservan el mismo nivel de vaguedad que el original y profundiza tu explicación.",
      review: "Cada campo tiene un problema de vaguedad: 'Documento' no es un título, 'Ana' no identifica a una persona, '2026' no es una fecha completa, '1' no es un código funcional, y 'Vario' no es un asunto. Propón valores específicos y explica por qué.",
    },
  },
  {
    id: 20,
    category: "Caso integrador final",
    kind: "capstone",
    scenario:
      "Una institución pública está organizando un conjunto de documentos electrónicos que actualmente presentan problemas de identificación, recuperación y contexto. Algunos documentos tienen títulos genéricos, otros no tienen unidad responsable, algunos carecen de fecha completa y no todos están relacionados con su expediente.",
    prompt:
      "Como responsable de gestión documental, ¿qué información de metadatos propondrías registrar para mejorar la gestión de estos documentos? Propón al menos 8 metadatos indicando su finalidad, selecciona los que consideras indispensables y justifica tu propuesta.",
    points: 1,
    minRows: 8,
    justifyMinWords: 15,
    expectedSummary: "Al menos 8 metadatos (identificación, descripción, gestión, contexto y preservación) con su finalidad explícita, una selección razonada de los indispensables y una justificación que integre los problemas del caso.",
    feedbackByVerdict: {
      correct: "Correcto: propones un conjunto amplio y variado de metadatos, indicas su finalidad con claridad, seleccionas con criterio los indispensables y tu justificación conecta la propuesta con los problemas de identificación, recuperación y contexto planteados en el caso — una síntesis sólida de lo trabajado en la semana.",
      partial: "Tu propuesta tiene elementos valiosos, pero podrías ampliar la variedad de metadatos (cubriendo identificación, descripción, gestión, contexto y preservación), precisar mejor la finalidad de cada uno, o fortalecer la justificación final.",
      review: "Retoma el caso: los problemas son de identificación (títulos genéricos), contexto (falta unidad responsable), descripción (fechas incompletas) y relación documento-expediente. Propón al menos 8 metadatos que resuelvan específicamente esos problemas, indicando su finalidad.",
    },
  },
];

export const TOTAL_QUESTIONS_4 = practice4Questions.length;
export const MAX_SCORE_4 = practice4Questions.reduce((sum, q) => sum + q.points, 0);
