import {
  Activity,
  AlertCircle,
  Archive,
  ArrowRightLeft,
  AudioLines,
  BellRing,
  BookOpen,
  BookOpenCheck,
  ClipboardList,
  Database,
  DatabaseZap,
  EyeOff,
  FileCode,
  FilePlus,
  FileSearch,
  FileSignature,
  FileStack,
  FileText,
  FileType,
  FileX,
  FolderKanban,
  FolderOpen,
  FolderTree,
  FolderX,
  GitCompareArrows,
  HelpCircle,
  History,
  Image,
  Inbox,
  KeyRound,
  Landmark,
  LayoutGrid,
  Link2,
  Lock,
  Mail,
  MousePointerClick,
  Radar,
  ReceiptText,
  RefreshCw,
  Route,
  Scale,
  ScanLine,
  ServerCrash,
  Sheet,
  ShieldAlert,
  ShieldCheck,
  Stamp,
  Tags,
  Target,
  Users,
  Video,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon map for lesson/week data (which stores icon names as plain
 * strings). Explicit imports keep the bundle tree-shakeable — importing
 * lucide-react's full `icons` barrel would pull in every icon in the library.
 * Add an entry here whenever a new lesson icon name is introduced.
 */
const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  Archive,
  ArrowRightLeft,
  AudioLines,
  BellRing,
  BookOpen,
  BookOpenCheck,
  ClipboardList,
  Database,
  DatabaseZap,
  EyeOff,
  FileCode,
  FilePlus,
  FileSearch,
  FileSignature,
  FileStack,
  FileText,
  FileType,
  FileX,
  FolderKanban,
  FolderOpen,
  FolderTree,
  FolderX,
  GitCompareArrows,
  HelpCircle,
  History,
  Image,
  Inbox,
  KeyRound,
  Landmark,
  LayoutGrid,
  Link2,
  Lock,
  Mail,
  MousePointerClick,
  Radar,
  ReceiptText,
  RefreshCw,
  Route,
  Scale,
  ScanLine,
  ServerCrash,
  Sheet,
  ShieldAlert,
  ShieldCheck,
  Stamp,
  Tags,
  Target,
  Users,
  Video,
  Workflow,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? HelpCircle;
}
