import type { PracticeQuestion } from "./practice.types";

export const practiceQuestions: PracticeQuestion[] = [
  {
    id: 1,
    type: "single",
    category: "Recepción",
    scenario: "Una institución recibe una solicitud relacionada con un procedimiento administrativo mediante un canal institucional.",
    prompt: "¿Qué debería ocurrir inicialmente con el documento?",
    options: [
      { id: "a", label: "Guardarlo en una carpeta personal." },
      { id: "b", label: "Incorporarlo al proceso de gestión documental y registrarlo." },
      { id: "c", label: "Enviarlo directamente por correo electrónico." },
      { id: "d", label: "Imprimirlo y archivarlo físicamente." },
    ],
    correct: "b",
    feedbackCorrect: "El documento debe incorporarse al proceso de gestión documental correspondiente y registrarse para permitir su identificación, control y seguimiento.",
    feedbackIncorrect: "El documento debe incorporarse al proceso de gestión documental correspondiente y registrarse para permitir su identificación, control y seguimiento.",
    points: 5,
  },
  {
    id: 2,
    type: "multi",
    category: "Registro",
    scenario: "El documento será registrado en el SGD.",
    prompt: "¿Qué información sería pertinente para identificar y contextualizar el documento? Selecciona todas las correctas.",
    options: [
      { id: "a", label: "Fecha de recepción" },
      { id: "b", label: "Productor o remitente" },
      { id: "c", label: "Asunto" },
      { id: "d", label: "Tipo documental" },
      { id: "e", label: "Identificador" },
      { id: "f", label: "Color de pantalla" },
      { id: "g", label: "Tamaño del monitor" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    feedbackCorrect: "Los elementos seleccionados permiten identificar y contextualizar el documento. El color de pantalla y el tamaño del monitor no constituyen información documental relevante para esta decisión.",
    feedbackIncorrect: "Los elementos seleccionados permiten identificar y contextualizar el documento. El color de pantalla y el tamaño del monitor no constituyen información documental relevante para esta decisión.",
    points: 5,
  },
  {
    id: 3,
    type: "single",
    category: "Documento y expediente",
    scenario: "El documento recibido corresponde a un asunto que ya tiene otros documentos relacionados.",
    prompt: "¿Qué debería analizar el responsable?",
    options: [
      { id: "a", label: "Crear una carpeta personal." },
      { id: "b", label: "Determinar si corresponde incorporarlo a un expediente existente." },
      { id: "c", label: "Cambiar el nombre del archivo." },
      { id: "d", label: "Guardarlo en otra computadora." },
    ],
    correct: "b",
    feedbackCorrect: "Antes de crear una nueva agrupación documental debe analizarse el contexto y la relación del documento con un expediente existente.",
    feedbackIncorrect: "Antes de crear una nueva agrupación documental debe analizarse el contexto y la relación del documento con un expediente existente.",
    points: 5,
  },
  {
    id: 4,
    type: "single",
    category: "Contexto",
    contextItems: ["Solicitud", "Informe", "Respuesta", "Anexo"],
    prompt: "Antes de incorporarlos a un expediente, ¿qué debería verificarse?",
    options: [
      { id: "a", label: "El tamaño de cada archivo." },
      { id: "b", label: "La relación documental y el contexto del asunto." },
      { id: "c", label: "El color del archivo." },
      { id: "d", label: "La computadora donde fueron creados." },
    ],
    correct: "b",
    feedbackCorrect: "La relación documental y el contexto del asunto son lo que determina si estos documentos pertenecen a un mismo expediente.",
    feedbackIncorrect: "La relación documental y el contexto del asunto son lo que determina si estos documentos pertenecen a un mismo expediente.",
    points: 5,
  },
  {
    id: 5,
    type: "single",
    category: "Trámite",
    scenario: "Una solicitud ya fue registrada y debe ser atendida por la unidad responsable.",
    prompt: "¿Qué acción corresponde analizar?",
    options: [
      { id: "a", label: "Eliminar el documento original." },
      { id: "b", label: "Derivar el documento al responsable del trámite según el proceso." },
      { id: "c", label: "Cambiar el nombre del documento sin registrar el cambio." },
      { id: "d", label: "Guardarlo solamente en el escritorio del usuario." },
    ],
    correct: "b",
    feedbackCorrect: "El documento debe continuar dentro del flujo correspondiente, manteniendo identificación, contexto y evidencia de la actuación.",
    feedbackIncorrect: "El documento debe continuar dentro del flujo correspondiente, manteniendo identificación, contexto y evidencia de la actuación.",
    points: 5,
  },
  {
    id: 6,
    type: "multi",
    category: "Trazabilidad",
    scenario: "El responsable deriva el documento a otra unidad.",
    prompt: "¿Qué información debería quedar registrada como evidencia de la actuación? Selecciona las opciones pertinentes.",
    options: [
      { id: "a", label: "Usuario que realizó la acción" },
      { id: "b", label: "Fecha y hora" },
      { id: "c", label: "Unidad de destino" },
      { id: "d", label: "Acción realizada" },
      { id: "e", label: "Color de pantalla" },
    ],
    correct: ["a", "b", "c", "d"],
    feedbackCorrect: "Estos cuatro elementos permiten reconstruir quién actuó, cuándo, hacia dónde y qué hizo — la base de la trazabilidad.",
    feedbackIncorrect: "Estos cuatro elementos permiten reconstruir quién actuó, cuándo, hacia dónde y qué hizo — la base de la trazabilidad.",
    points: 5,
  },
  {
    id: 7,
    type: "single",
    category: "Emisión",
    scenario: "Después de analizar una solicitud, la unidad responsable debe generar un documento de respuesta.",
    prompt: "¿Qué proceso está ocurriendo principalmente?",
    options: [
      { id: "a", label: "Recepción." },
      { id: "b", label: "Registro inicial." },
      { id: "c", label: "Emisión." },
      { id: "d", label: "Eliminación." },
    ],
    correct: "c",
    feedbackCorrect: "Generar un documento de respuesta como resultado de una actuación corresponde al proceso de emisión.",
    feedbackIncorrect: "Generar un documento de respuesta como resultado de una actuación corresponde al proceso de emisión.",
    points: 5,
  },
  {
    id: 8,
    type: "single",
    category: "Despacho",
    scenario: "El documento de respuesta ha sido aprobado y debe ser enviado al destinatario.",
    prompt: "¿Qué etapa corresponde?",
    options: [
      { id: "a", label: "Despacho." },
      { id: "b", label: "Clasificación." },
      { id: "c", label: "Digitalización." },
      { id: "d", label: "Eliminación." },
    ],
    correct: "a",
    feedbackCorrect: "Enviar o poner a disposición un documento aprobado corresponde a la etapa de despacho.",
    feedbackIncorrect: "Enviar o poner a disposición un documento aprobado corresponde a la etapa de despacho.",
    points: 5,
  },
  {
    id: 9,
    type: "single",
    category: "Expediente electrónico",
    scenario: "EXPEDIENTE 2026-015",
    contextItems: ["Solicitud.pdf", "Informe.pdf", "Respuesta.pdf", "Anexo.pdf"],
    prompt: "¿Qué permite determinar que estos documentos pueden formar parte de un mismo expediente?",
    options: [
      { id: "a", label: "Que todos tienen extensión PDF." },
      { id: "b", label: "Que están guardados en la misma computadora." },
      { id: "c", label: "Su relación con el mismo asunto/proceso y contexto documental." },
      { id: "d", label: "Que todos tienen el mismo tamaño." },
    ],
    correct: "c",
    feedbackCorrect: "La pertenencia a un expediente depende de la relación con el mismo asunto, procedimiento y contexto documental — no de atributos técnicos del archivo.",
    feedbackIncorrect: "La pertenencia a un expediente depende de la relación con el mismo asunto, procedimiento y contexto documental — no de atributos técnicos del archivo.",
    points: 5,
  },
  {
    id: 10,
    type: "single",
    category: "Expediente",
    scenario: "Un usuario encuentra un documento que parece relacionado con un expediente existente, pero no existe información suficiente para confirmar la relación.",
    prompt: "¿Qué debería hacer?",
    options: [
      { id: "a", label: "Incorporarlo inmediatamente." },
      { id: "b", label: "Eliminarlo." },
      { id: "c", label: "Analizar y verificar su contexto antes de incorporarlo." },
      { id: "d", label: "Cambiarle el nombre." },
    ],
    correct: "c",
    feedbackCorrect: "Un profesional no debería inventar contexto documental. Cuando la información es insuficiente, primero debe verificarse la relación documental.",
    feedbackIncorrect: "Un profesional no debería inventar contexto documental. Cuando la información es insuficiente, primero debe verificarse la relación documental.",
    points: 5,
  },
  {
    id: 11,
    type: "multi",
    category: "Problema del expediente",
    scenario: "EXPEDIENTE 2026-015",
    contextItems: ["final.pdf", "documento.pdf", "nuevo.pdf", "scan001.pdf", "final2.pdf", "respuesta.pdf"],
    prompt: "¿Qué problemas pueden identificarse? Selecciona todas las correctas.",
    options: [
      { id: "a", label: "Nombres ambiguos" },
      { id: "b", label: "Dificultad para identificar contenido" },
      { id: "c", label: "Posibles duplicidades" },
      { id: "d", label: "Dificultad para establecer la secuencia" },
      { id: "e", label: "Falta de contexto" },
      { id: "f", label: "Todos los documentos son incorrectos automáticamente" },
    ],
    correct: ["a", "b", "c", "d", "e"],
    feedbackCorrect: "Los nombres genéricos generan estos cinco problemas archivísticos reales. Que un nombre sea ambiguo no significa que el documento sea \"incorrecto\": el problema es de identificación, no de validez.",
    feedbackIncorrect: "Los nombres genéricos generan estos cinco problemas archivísticos reales. Que un nombre sea ambiguo no significa que el documento sea \"incorrecto\": el problema es de identificación, no de validez.",
    points: 5,
  },
  {
    id: 12,
    type: "order",
    category: "Ordenamiento",
    scenario: "Estos documentos corresponden a un mismo expediente y están numerados según el momento en que se produjeron dentro del trámite.",
    prompt: "Ordena los documentos según la secuencia en que ocurrieron.",
    items: [
      { id: "d4", label: "Documento 4" },
      { id: "d1", label: "Documento 1" },
      { id: "d5", label: "Documento 5" },
      { id: "d2", label: "Documento 2" },
      { id: "d3", label: "Documento 3" },
    ],
    correctOrder: ["d1", "d2", "d3", "d4", "d5"],
    feedbackCorrect: "El orden numérico refleja la secuencia en que los documentos se produjeron dentro del trámite.",
    feedbackIncorrect: "El orden numérico refleja la secuencia en que los documentos se produjeron dentro del trámite.",
    points: 5,
    openQuestion: "¿Por qué elegiste este orden?",
  },
  {
    id: 13,
    type: "single",
    category: "Ordenamiento digital",
    scenario: "Un expediente electrónico contiene varios documentos que corresponden a diferentes momentos de un mismo trámite.",
    prompt: "¿Qué debería analizarse para establecer el orden?",
    options: [
      { id: "a", label: "Solamente el tamaño de los archivos." },
      { id: "b", label: "El contexto documental y los criterios de ordenamiento aplicables." },
      { id: "c", label: "El nombre del computador." },
      { id: "d", label: "El color de los documentos." },
    ],
    correct: "b",
    feedbackCorrect: "El orden debe responder al contexto documental y a los criterios de ordenamiento aplicables, no a atributos técnicos irrelevantes.",
    feedbackIncorrect: "El orden debe responder al contexto documental y a los criterios de ordenamiento aplicables, no a atributos técnicos irrelevantes.",
    points: 5,
  },
  {
    id: 14,
    type: "single",
    category: "Foliación",
    scenario: "Un conjunto de documentos digitalizados debe ser organizado y controlado dentro de un expediente.",
    prompt: "¿Qué debe considerarse al aplicar criterios de foliación u ordenamiento digital?",
    options: [
      { id: "a", label: "Las reglas y el contexto documental aplicables." },
      { id: "b", label: "El tamaño de la pantalla." },
      { id: "c", label: "El color de los archivos." },
      { id: "d", label: "El nombre del monitor." },
    ],
    correct: "a",
    feedbackCorrect: "La foliación y el ordenamiento deben responder a las reglas y al contexto documental aplicables al tipo de expediente y sistema — no existe una única técnica universal.",
    feedbackIncorrect: "La foliación y el ordenamiento deben responder a las reglas y al contexto documental aplicables al tipo de expediente y sistema — no existe una única técnica universal.",
    points: 5,
  },
  {
    id: 15,
    type: "single",
    category: "Clasificación",
    scenario: "Documento: \"Informe sobre adquisición de equipos informáticos.\"",
    prompt: "¿Qué debería analizarse antes de asignar una clasificación?",
    options: [
      { id: "a", label: "Tamaño del PDF." },
      { id: "b", label: "Función, actividad y contexto documental." },
      { id: "c", label: "Nombre del archivo." },
      { id: "d", label: "Usuario que abrió el documento." },
    ],
    correct: "b",
    feedbackCorrect: "La clasificación relaciona el documento con la función, actividad y contexto documental correspondiente, no con su nombre de archivo.",
    feedbackIncorrect: "La clasificación relaciona el documento con la función, actividad y contexto documental correspondiente, no con su nombre de archivo.",
    points: 5,
  },
  {
    id: 16,
    type: "single",
    category: "Clasificación",
    scenario: "Dos documentos tienen títulos similares, pero fueron producidos por unidades diferentes y corresponden a actividades diferentes.",
    prompt: "¿Es suficiente el título para determinar su clasificación?",
    options: [
      { id: "a", label: "Sí." },
      { id: "b", label: "No." },
    ],
    correct: "b",
    feedbackCorrect: "El título por sí solo no basta: la clasificación depende de la función y actividad que originó cada documento, no de la semejanza textual del título.",
    feedbackIncorrect: "El título por sí solo no basta: la clasificación depende de la función y actividad que originó cada documento, no de la semejanza textual del título.",
    points: 5,
    openQuestion: "Explica qué información adicional necesitarías.",
  },
  {
    id: 17,
    type: "single",
    category: "Organización",
    prompt: "¿Qué significa organizar documentalmente un conjunto de documentos?",
    options: [
      { id: "a", label: "Guardarlos todos en una carpeta." },
      { id: "b", label: "Mantener una estructura coherente de acuerdo con el contexto y las relaciones documentales." },
      { id: "c", label: "Cambiarles el nombre." },
      { id: "d", label: "Comprimirlos en ZIP." },
    ],
    correct: "b",
    feedbackCorrect: "Organizar implica mantener una estructura coherente según el contexto y las relaciones documentales — no es una acción puramente física o técnica.",
    feedbackIncorrect: "Organizar implica mantener una estructura coherente según el contexto y las relaciones documentales — no es una acción puramente física o técnica.",
    points: 5,
  },
  {
    id: 18,
    type: "single",
    category: "Descripción",
    scenario: "EXP-2026-0045",
    prompt: "¿Es suficiente este identificador para comprender y recuperar adecuadamente el expediente?",
    options: [
      { id: "a", label: "Sí." },
      { id: "b", label: "No." },
    ],
    correct: "b",
    feedbackCorrect: "Un identificador por sí solo no permite comprender de qué trata el expediente ni recuperarlo con criterio; se necesita información descriptiva adicional.",
    feedbackIncorrect: "Un identificador por sí solo no permite comprender de qué trata el expediente ni recuperarlo con criterio; se necesita información descriptiva adicional.",
    points: 5,
    openQuestion: "¿Qué otros elementos descriptivos considerarías?",
    openSuggestions: ["Título", "Fechas", "Productor", "Asunto", "Alcance", "Relaciones"],
  },
  {
    id: 19,
    type: "match",
    category: "Diferenciar conceptos",
    prompt: "Relaciona cada concepto con su definición.",
    concepts: [
      { id: "clasificacion", label: "Clasificación" },
      { id: "organizacion", label: "Organización" },
      { id: "descripcion", label: "Descripción" },
    ],
    definitions: [
      { id: "clasificacion", label: "Determinar dónde pertenece documentalmente." },
      { id: "organizacion", label: "Mantener una estructura y relaciones documentales coherentes." },
      { id: "descripcion", label: "Representar información que facilite la identificación y recuperación." },
    ],
    correctPairs: { clasificacion: "clasificacion", organizacion: "organizacion", descripcion: "descripcion" },
    feedbackCorrect: "Cada concepto responde a una pregunta distinta: dónde pertenece, cómo se estructura y cómo se representa para recuperarlo.",
    feedbackIncorrect: "Cada concepto responde a una pregunta distinta: dónde pertenece, cómo se estructura y cómo se representa para recuperarlo.",
    points: 5,
  },
  {
    id: 20,
    type: "multi",
    category: "Caso final",
    scenario: "EXPEDIENTE 2026-0045",
    contextItems: ["Solicitud.pdf", "Informe.pdf", "Informe_final.pdf", "Respuesta.pdf", "Anexo1.pdf", "scan002.pdf", "documento.pdf"],
    prompt:
      "Algunos documentos tienen nombres ambiguos, existen documentos relacionados, no todos tienen suficiente información contextual, existe incertidumbre sobre el orden y algunos documentos podrían ser duplicados.\n\nUsted forma parte del equipo encargado de revisar este expediente antes de su cierre. ¿Qué acciones realizaría? Selecciona todas las correctas.",
    options: [
      { id: "a", label: "Verificar la identificación de los documentos." },
      { id: "b", label: "Verificar la relación documental." },
      { id: "c", label: "Revisar el ordenamiento." },
      { id: "d", label: "Identificar posibles duplicidades." },
      { id: "e", label: "Revisar la clasificación." },
      { id: "f", label: "Completar la información descriptiva necesaria." },
      { id: "g", label: "Eliminar inmediatamente todos los documentos dudosos." },
      { id: "h", label: "Cambiar todos los nombres sin revisar su contexto." },
    ],
    correct: ["a", "b", "c", "d", "e", "f"],
    feedbackCorrect: "Un cierre responsable exige verificar identificación, relación, orden, duplicidad, clasificación y descripción — nunca eliminar o renombrar sin antes revisar el contexto.",
    feedbackIncorrect: "Un cierre responsable exige verificar identificación, relación, orden, duplicidad, clasificación y descripción — nunca eliminar o renombrar sin antes revisar el contexto.",
    points: 5,
    openQuestion: "Explica cuál consideras que es el principal problema del expediente y qué acción priorizarías.",
  },
];

export const TOTAL_QUESTIONS = practiceQuestions.length;
export const MAX_SCORE = practiceQuestions.reduce((sum, q) => sum + q.points, 0);
